config/routes.rb
Rails.application.routes.draw do
  get 'boxes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  resources :items, only: [:index]
  root 'customers#index'
  resources :boxes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :item, presence: true
  validates :item, uniqueness: { scope: :customer }
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  include BoxesHelper

  def index
  	@boxes = available_boxes()
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, only: [:show, :edit, :update, :destroy], except: [:boxes]

  def index
  	@customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'edit'
    end
  end

  def boxes
    available_boxes()
  end

  private

  def find_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
  BOXES_API="http://tuskermarvel.com/boxes.json"

  def available_boxes()
    result = Net::HTTP.get(URI.parse(BOXES_API))
    json = JSON.parse(result)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/boxes/index.html.erb
<h1>Available Boxes (next Shipment)</h1>

  <% @boxes.each do |box| %>
    <div class="box">
      <p>
        <strong>Box Code:</strong>
        <%= box['code'] %>
      </p>
      <div class="box_content">
        <p>
          <strong>Content:</strong>
        </p>
          <% box['contents'].each do |c| %>
            <div class="content_item">
               <%= c.to_s %>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Customer Edit</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customers Listing</h1>


<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr class="<%= cycle('line_odd', 'line_even') %>">
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.city %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<h1>Customer</h1>
<p>
  <strong>First Name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<h2>Items Received:</h2>
<% @customer.items.each do |item| %>
  <p>
    <strong>Item Description:</strong>
    <%= item.item %>
  </p>
<% end %>

<h2>Next Box to be Delivered:</h2>


<%= link_to 'Back', customers_path %> |
<%= link_to "Edit", edit_customer_path(@customer) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuskerAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav id="horzNav">
    <p>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Customers', customers_path %>
      <%= link_to 'Boxes', boxes_path %>
    </p>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>